# Vanilla Gradient Descent

implementation of gradient descent using only numpy

Notes:

<a href>http://cs229.stanford.edu/notes/cs229-notes1.pdf</a>

In [1]:
import numpy as np
from functools import reduce
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
data = pd.read_csv('banks.csv')

In [10]:
data = data.drop(['Financial Institution Number', 'Insurance Fund','Institution Name', 'Institution Type', 'Headquarters', 'Failure Date', 'Certificate Number', 'Transaction Type', 'Estimated Loss (2015)'], axis=1)
data.drop(['Charter Type',], axis=1, inplace=True)
data = data[data['Total Assets'] < 2000263.0]
data = data[data['Total Assets'] > 1000000]
data = data[data['Total Deposits'] < 2000263.0]
data = data[data['Total Deposits'] > 1000000]

In [15]:
data.columns

Index(['Total Deposits', 'Total Assets'], dtype='object')

In [141]:
np.random.rand(1,1)

array([[ 0.34133342]])

In [150]:
class gradient_descent:
    
    def __init__(self, x, y, epochs, rate, debug=False):
        self.x = np.array([x])
        self.y = np.array([y])
        self.epochs = epochs
        self.learning_rate = rate
        self.debug = debug
        self.model_thetas = [np.random.rand(self.x.shape[1],1)[0]]
        self.model_costs = []
        self.model_hypothesis = []
        
    def set_thetas(self, theta):
        self.model_thetas = theta
        
    def thetas(self):
        return self.model_thetas
    
    def costs(self):
        return self.model_costs
    
    def hypo(self):
        return self.model_hypothesis
    
    def minimized(self):
        output = {
            'thetas': self.model_thetas[-1],
            'costs': self.model_costs[-1],
            'hypothesis': self.model_hypothesis[-1]
        }
        return output
    
    def compute(self):
        for i in range(self.epochs):
            print(i)
            hypothesis = self.model_thetas[-1].transpose()*self.x
            new_cost = np.divide(np.sum(np.square(np.subtract(hypothesis, self.y))),self.x.shape[1])
            MLE = np.subtract(self.y, hypothesis).dot(self.x.reshape(self.y.shape[1],1))[0]
            new_theta = np.add(self.model_thetas[-1],np.multiply(self.learning_rate,  MLE))
            self.model_hypothesis.append(hypothesis)
            self.model_costs.append(new_cost)
            self.model_thetas.append(new_theta)

### Use the class

In [151]:
house = gradient_descent(x=data['Total Deposits'][:4], y=data['Total Assets'][:4], epochs=3, rate=1, debug=False)

In [152]:
house.compute()

0
1
2


In [153]:
house.costs()

[1192200422935.3623, 1.038967740024379e+38, 9.284276858006052e+63]

In [154]:
house.thetas()

[array([ 0.4218129]),
 array([  6.63047317e+12]),
 array([ -6.26783467e+25]),
 array([  5.92502984e+38])]

In [155]:
house.hypo()

[array([[ 632191.2373136 ,  548924.52761445,  761908.40515796,
          632819.31671879]]),
 array([[  9.93740841e+18,   8.62853974e+18,   1.19764314e+19,
           9.94728118e+18]]),
 array([[ -9.39390467e+31,  -8.15662157e+31,  -1.13214080e+32,
          -9.40323748e+31]])]

In [131]:
house.minimized()

{'costs': 4.9331714812095866e+64,
 'hypothesis': array([[[[ -1.08269272e+32,  -9.40089891e+31,  -1.30484676e+32,
            -1.08376837e+32]],
 
         [[ -1.08269272e+32,  -9.40089891e+31,  -1.30484676e+32,
            -1.08376837e+32]],
 
         [[ -1.08269272e+32,  -9.40089891e+31,  -1.30484676e+32,
            -1.08376837e+32]],
 
         [[ -1.08269272e+32,  -9.40089891e+31,  -1.30484676e+32,
            -1.08376837e+32]]]]),
 'thetas': array([[[[[  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38]],
 
          [[  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38]],
 
          [[  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38]],
 
          [[  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38],
           [  6.82888204e+38]]]]])}